version: "3.9"
services:
  app:
    build: .
    image: jocasta-polls-api:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      # Allow override from env_file; keep as examples
      - NODE_ENV=production
      - PORT=8000
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
